# Generated by Django 2.0.1 on 2018-06-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='comments',
            field=models.CharField(default='', max_length=200, verbose_name='Comments'),
        ),
    ]
